/* guid-helpers.c generated by valac 0.32.0.45-49b63, the Vala compiler
 * generated from guid-helpers.vala, do not modify */

/* This file is part of GNOME Games. License: GPLv3*/

#include <glib.h>
#include <glib-object.h>
#include <libevdev/libevdev.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <sys/types.h>
#include <errno.h>
#include <unistd.h>


#define LIB_GAMEPAD_TYPE_LINUX_GUID_HELPERS (lib_gamepad_linux_guid_helpers_get_type ())
#define LIB_GAMEPAD_LINUX_GUID_HELPERS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LIB_GAMEPAD_TYPE_LINUX_GUID_HELPERS, LibGamepadLinuxGuidHelpers))
#define LIB_GAMEPAD_LINUX_GUID_HELPERS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LIB_GAMEPAD_TYPE_LINUX_GUID_HELPERS, LibGamepadLinuxGuidHelpersClass))
#define LIB_GAMEPAD_IS_LINUX_GUID_HELPERS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LIB_GAMEPAD_TYPE_LINUX_GUID_HELPERS))
#define LIB_GAMEPAD_IS_LINUX_GUID_HELPERS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LIB_GAMEPAD_TYPE_LINUX_GUID_HELPERS))
#define LIB_GAMEPAD_LINUX_GUID_HELPERS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LIB_GAMEPAD_TYPE_LINUX_GUID_HELPERS, LibGamepadLinuxGuidHelpersClass))

typedef struct _LibGamepadLinuxGuidHelpers LibGamepadLinuxGuidHelpers;
typedef struct _LibGamepadLinuxGuidHelpersClass LibGamepadLinuxGuidHelpersClass;
typedef struct _LibGamepadLinuxGuidHelpersPrivate LibGamepadLinuxGuidHelpersPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _libevdev_free0(var) ((var == NULL) ? NULL : (var = (libevdev_free (var), NULL)))

struct _LibGamepadLinuxGuidHelpers {
	GObject parent_instance;
	LibGamepadLinuxGuidHelpersPrivate * priv;
};

struct _LibGamepadLinuxGuidHelpersClass {
	GObjectClass parent_class;
};


static gpointer lib_gamepad_linux_guid_helpers_parent_class = NULL;

GType lib_gamepad_linux_guid_helpers_get_type (void) G_GNUC_CONST;
enum  {
	LIB_GAMEPAD_LINUX_GUID_HELPERS_DUMMY_PROPERTY
};
gchar* lib_gamepad_linux_guid_helpers_from_dev (struct libevdev* dev);
gchar* lib_gamepad_uint16s_to_hex_string (guint16* data, int data_length1);
gchar* lib_gamepad_linux_guid_helpers_from_file (const gchar* file_name, GError** error);
LibGamepadLinuxGuidHelpers* lib_gamepad_linux_guid_helpers_new (void);
LibGamepadLinuxGuidHelpers* lib_gamepad_linux_guid_helpers_construct (GType object_type);


gchar* lib_gamepad_linux_guid_helpers_from_dev (struct libevdev* dev) {
	gchar* result = NULL;
	guint16 guid[8] = {0};
	struct libevdev* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	guint16 _tmp4_ = 0U;
	guint16 _tmp5_ = 0U;
	struct libevdev* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	gint _tmp9_ = 0;
	guint16 _tmp10_ = 0U;
	guint16 _tmp11_ = 0U;
	struct libevdev* _tmp12_ = NULL;
	gint _tmp13_ = 0;
	gint _tmp14_ = 0;
	gint _tmp15_ = 0;
	guint16 _tmp16_ = 0U;
	guint16 _tmp17_ = 0U;
	struct libevdev* _tmp18_ = NULL;
	gint _tmp19_ = 0;
	gint _tmp20_ = 0;
	gint _tmp21_ = 0;
	guint16 _tmp22_ = 0U;
	guint16 _tmp23_ = 0U;
	gchar* _tmp24_ = NULL;
	g_return_val_if_fail (dev != NULL, NULL);
	_tmp0_ = dev;
	_tmp1_ = libevdev_get_id_bustype (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = GINT_TO_LE (_tmp2_);
	guid[0] = (guint16) _tmp3_;
	_tmp4_ = guid[0];
	guid[1] = (guint16) 0;
	_tmp5_ = guid[1];
	_tmp6_ = dev;
	_tmp7_ = libevdev_get_id_vendor (_tmp6_);
	_tmp8_ = _tmp7_;
	_tmp9_ = GINT_TO_LE (_tmp8_);
	guid[2] = (guint16) _tmp9_;
	_tmp10_ = guid[2];
	guid[3] = (guint16) 0;
	_tmp11_ = guid[3];
	_tmp12_ = dev;
	_tmp13_ = libevdev_get_id_product (_tmp12_);
	_tmp14_ = _tmp13_;
	_tmp15_ = GINT_TO_LE (_tmp14_);
	guid[4] = (guint16) _tmp15_;
	_tmp16_ = guid[4];
	guid[5] = (guint16) 0;
	_tmp17_ = guid[5];
	_tmp18_ = dev;
	_tmp19_ = libevdev_get_id_version (_tmp18_);
	_tmp20_ = _tmp19_;
	_tmp21_ = GINT_TO_LE (_tmp20_);
	guid[6] = (guint16) _tmp21_;
	_tmp22_ = guid[6];
	guid[7] = (guint16) 0;
	_tmp23_ = guid[7];
	_tmp24_ = lib_gamepad_uint16s_to_hex_string (guid, 8);
	result = _tmp24_;
	return result;
}


static const gchar* string_to_string (const gchar* self) {
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


gchar* lib_gamepad_linux_guid_helpers_from_file (const gchar* file_name, GError** error) {
	gchar* result = NULL;
	gint fd = 0;
	const gchar* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	struct libevdev* dev = NULL;
	struct libevdev* _tmp12_ = NULL;
	struct libevdev* _tmp13_ = NULL;
	gint _tmp14_ = 0;
	gint _tmp15_ = 0;
	gchar* guid = NULL;
	struct libevdev* _tmp25_ = NULL;
	gchar* _tmp26_ = NULL;
	gint _tmp27_ = 0;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (file_name != NULL, NULL);
	_tmp0_ = file_name;
	_tmp1_ = open (_tmp0_, O_RDONLY | O_NONBLOCK, (mode_t) 0);
	fd = _tmp1_;
	_tmp2_ = fd;
	if (_tmp2_ < 0) {
		const gchar* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
		gint _tmp5_ = 0;
		const gchar* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		GError* _tmp10_ = NULL;
		GError* _tmp11_ = NULL;
		_tmp3_ = file_name;
		_tmp4_ = string_to_string (_tmp3_);
		_tmp5_ = errno;
		_tmp6_ = strerror (_tmp5_);
		_tmp7_ = string_to_string (_tmp6_);
		_tmp8_ = g_strconcat ("Unable to open file ", _tmp4_, ": ", _tmp7_, NULL);
		_tmp9_ = _tmp8_;
		_tmp10_ = g_error_new_literal (G_FILE_ERROR, G_FILE_ERROR_FAILED, _tmp9_);
		_tmp11_ = _tmp10_;
		_g_free0 (_tmp9_);
		_inner_error_ = _tmp11_;
		if (_inner_error_->domain == G_FILE_ERROR) {
			g_propagate_error (error, _inner_error_);
			return NULL;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp12_ = libevdev_new ();
	dev = _tmp12_;
	_tmp13_ = dev;
	_tmp14_ = fd;
	_tmp15_ = libevdev_set_fd (_tmp13_, _tmp14_);
	if (_tmp15_ < 0) {
		const gchar* _tmp16_ = NULL;
		const gchar* _tmp17_ = NULL;
		gint _tmp18_ = 0;
		const gchar* _tmp19_ = NULL;
		const gchar* _tmp20_ = NULL;
		gchar* _tmp21_ = NULL;
		gchar* _tmp22_ = NULL;
		GError* _tmp23_ = NULL;
		GError* _tmp24_ = NULL;
		_tmp16_ = file_name;
		_tmp17_ = string_to_string (_tmp16_);
		_tmp18_ = errno;
		_tmp19_ = strerror (_tmp18_);
		_tmp20_ = string_to_string (_tmp19_);
		_tmp21_ = g_strconcat ("Evdev error on opening file ", _tmp17_, ": ", _tmp20_, NULL);
		_tmp22_ = _tmp21_;
		_tmp23_ = g_error_new_literal (G_FILE_ERROR, G_FILE_ERROR_FAILED, _tmp22_);
		_tmp24_ = _tmp23_;
		_g_free0 (_tmp22_);
		_inner_error_ = _tmp24_;
		if (_inner_error_->domain == G_FILE_ERROR) {
			g_propagate_error (error, _inner_error_);
			_libevdev_free0 (dev);
			return NULL;
		} else {
			_libevdev_free0 (dev);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp25_ = dev;
	_tmp26_ = lib_gamepad_linux_guid_helpers_from_dev (_tmp25_);
	guid = _tmp26_;
	_tmp27_ = fd;
	close (_tmp27_);
	result = guid;
	_libevdev_free0 (dev);
	return result;
}


LibGamepadLinuxGuidHelpers* lib_gamepad_linux_guid_helpers_construct (GType object_type) {
	LibGamepadLinuxGuidHelpers * self = NULL;
	self = (LibGamepadLinuxGuidHelpers*) g_object_new (object_type, NULL);
	return self;
}


LibGamepadLinuxGuidHelpers* lib_gamepad_linux_guid_helpers_new (void) {
	return lib_gamepad_linux_guid_helpers_construct (LIB_GAMEPAD_TYPE_LINUX_GUID_HELPERS);
}


static void lib_gamepad_linux_guid_helpers_class_init (LibGamepadLinuxGuidHelpersClass * klass) {
	lib_gamepad_linux_guid_helpers_parent_class = g_type_class_peek_parent (klass);
}


static void lib_gamepad_linux_guid_helpers_instance_init (LibGamepadLinuxGuidHelpers * self) {
}


GType lib_gamepad_linux_guid_helpers_get_type (void) {
	static volatile gsize lib_gamepad_linux_guid_helpers_type_id__volatile = 0;
	if (g_once_init_enter (&lib_gamepad_linux_guid_helpers_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LibGamepadLinuxGuidHelpersClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lib_gamepad_linux_guid_helpers_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LibGamepadLinuxGuidHelpers), 0, (GInstanceInitFunc) lib_gamepad_linux_guid_helpers_instance_init, NULL };
		GType lib_gamepad_linux_guid_helpers_type_id;
		lib_gamepad_linux_guid_helpers_type_id = g_type_register_static (G_TYPE_OBJECT, "LibGamepadLinuxGuidHelpers", &g_define_type_info, 0);
		g_once_init_leave (&lib_gamepad_linux_guid_helpers_type_id__volatile, lib_gamepad_linux_guid_helpers_type_id);
	}
	return lib_gamepad_linux_guid_helpers_type_id__volatile;
}



