/* gamepad-event.c generated by valac 0.32.0.45-49b63, the Vala compiler
 * generated from gamepad-event.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <string.h>


#define LIB_GAMEPAD_TYPE_GAMEPAD_EVENT (lib_gamepad_gamepad_event_get_type ())

#define LIB_GAMEPAD_TYPE_INPUT_TYPE (lib_gamepad_input_type_get_type ())

#define LIB_GAMEPAD_TYPE_STANDARD_GAMEPAD_AXIS (lib_gamepad_standard_gamepad_axis_get_type ())

#define LIB_GAMEPAD_TYPE_STANDARD_GAMEPAD_BUTTON (lib_gamepad_standard_gamepad_button_get_type ())
typedef struct _LibGamepadGamepadEvent LibGamepadGamepadEvent;

typedef enum  {
	LIB_GAMEPAD_INPUT_TYPE_AXIS,
	LIB_GAMEPAD_INPUT_TYPE_BUTTON,
	LIB_GAMEPAD_INPUT_TYPE_INVALID
} LibGamepadInputType;

typedef enum  {
	LIB_GAMEPAD_STANDARD_GAMEPAD_AXIS_LEFT_X,
	LIB_GAMEPAD_STANDARD_GAMEPAD_AXIS_LEFT_Y,
	LIB_GAMEPAD_STANDARD_GAMEPAD_AXIS_RIGHT_X,
	LIB_GAMEPAD_STANDARD_GAMEPAD_AXIS_RIGHT_Y
} LibGamepadStandardGamepadAxis;

typedef enum  {
	LIB_GAMEPAD_STANDARD_GAMEPAD_BUTTON_A,
	LIB_GAMEPAD_STANDARD_GAMEPAD_BUTTON_B,
	LIB_GAMEPAD_STANDARD_GAMEPAD_BUTTON_X,
	LIB_GAMEPAD_STANDARD_GAMEPAD_BUTTON_Y,
	LIB_GAMEPAD_STANDARD_GAMEPAD_BUTTON_SHOULDER_L,
	LIB_GAMEPAD_STANDARD_GAMEPAD_BUTTON_SHOULDER_R,
	LIB_GAMEPAD_STANDARD_GAMEPAD_BUTTON_TRIGGER_L,
	LIB_GAMEPAD_STANDARD_GAMEPAD_BUTTON_TRIGGER_R,
	LIB_GAMEPAD_STANDARD_GAMEPAD_BUTTON_SELECT,
	LIB_GAMEPAD_STANDARD_GAMEPAD_BUTTON_START,
	LIB_GAMEPAD_STANDARD_GAMEPAD_BUTTON_STICK_L,
	LIB_GAMEPAD_STANDARD_GAMEPAD_BUTTON_STICK_R,
	LIB_GAMEPAD_STANDARD_GAMEPAD_BUTTON_DPAD_UP,
	LIB_GAMEPAD_STANDARD_GAMEPAD_BUTTON_DPAD_DOWN,
	LIB_GAMEPAD_STANDARD_GAMEPAD_BUTTON_DPAD_LEFT,
	LIB_GAMEPAD_STANDARD_GAMEPAD_BUTTON_DPAD_RIGHT,
	LIB_GAMEPAD_STANDARD_GAMEPAD_BUTTON_HOME,
	LIB_GAMEPAD_STANDARD_GAMEPAD_BUTTON_UNKNOWN
} LibGamepadStandardGamepadButton;

struct _LibGamepadGamepadEvent {
	LibGamepadInputType type;
	LibGamepadStandardGamepadAxis axis;
	LibGamepadStandardGamepadButton button;
};



GType lib_gamepad_gamepad_event_get_type (void) G_GNUC_CONST;
GType lib_gamepad_input_type_get_type (void) G_GNUC_CONST;
GType lib_gamepad_standard_gamepad_axis_get_type (void) G_GNUC_CONST;
GType lib_gamepad_standard_gamepad_button_get_type (void) G_GNUC_CONST;
LibGamepadGamepadEvent* lib_gamepad_gamepad_event_dup (const LibGamepadGamepadEvent* self);
void lib_gamepad_gamepad_event_free (LibGamepadGamepadEvent* self);


LibGamepadGamepadEvent* lib_gamepad_gamepad_event_dup (const LibGamepadGamepadEvent* self) {
	LibGamepadGamepadEvent* dup;
	dup = g_new0 (LibGamepadGamepadEvent, 1);
	memcpy (dup, self, sizeof (LibGamepadGamepadEvent));
	return dup;
}


void lib_gamepad_gamepad_event_free (LibGamepadGamepadEvent* self) {
	g_free (self);
}


GType lib_gamepad_gamepad_event_get_type (void) {
	static volatile gsize lib_gamepad_gamepad_event_type_id__volatile = 0;
	if (g_once_init_enter (&lib_gamepad_gamepad_event_type_id__volatile)) {
		GType lib_gamepad_gamepad_event_type_id;
		lib_gamepad_gamepad_event_type_id = g_boxed_type_register_static ("LibGamepadGamepadEvent", (GBoxedCopyFunc) lib_gamepad_gamepad_event_dup, (GBoxedFreeFunc) lib_gamepad_gamepad_event_free);
		g_once_init_leave (&lib_gamepad_gamepad_event_type_id__volatile, lib_gamepad_gamepad_event_type_id);
	}
	return lib_gamepad_gamepad_event_type_id__volatile;
}



